### ISSUE TITLE
Using `shadow!` creates an undesired runtime dependency on `libgit2`

### ISSUE THREAD

**Issue by metasim** [baoyachi/shadow-rs#183] opened 2024-09-17 20:28 UTC
It appears that when one includes `shadow-rs` in the `[dependencies]` section, it causes the generated executable to link against `libgit2` (as well as `const_format`, `is_debug`, `time` and `tzdb`), even though it's not needed. This is undesirable because of executable size bloat, as well as portability (when `libgit2` is dynamically linked, as is the default). 

Consider splitting project into two crates, one for the `build.rs` facilities, and the other for the `shadow!` macro. Workaround is to not include `shadow-rs` in the `[dependencies]` section and forego the use the macro, but rather insert the boilerplate manually:

```
pub mod build {
    include!(concat!(env!("OUT_DIR"), "/shadow.rs"));
}
```

**Comment by metasim** [comment] 2024-09-17 20:54
Actually, the workaround above doesn't work
```
236 | pub const VERSION:&str = shadow_rs::formatcp!(r#"
    |                          ^^^^^^^^^ use of undeclared crate or module `shadow_rs`
```

**Comment by baoyachi** [comment] 2024-09-18 06:22
Can the above description provide the complete configuration? 

> Actually, the workaround above doesn't work实际上，上面的解决方法并不起作用
> 
> ```
> 236 | pub const VERSION:&str = shadow_rs::formatcp!(r#"
>     |                          ^^^^^^^^^ use of undeclared crate or module `shadow_rs`
> ```
What is the reason for this error? I was not able to reproduce this issue.
@metasim

**Comment by metasim** [comment] 2024-09-18 13:16
You get that error if you remove `shadow-rs` from your `[dependencies]` section (so as to eliminate the dependency on libgit2`. I thought technically you could get away with that because I assumed the generated `shadow.rs` just contained string constants, but missed the use of `shadow_rs::formatcp`.

**Comment by baoyachi** [comment] 2024-09-19 02:26
Firstly, the git2 feature is optional. If you want to disable libgit2, you can use the following configuration:
```toml
...
[dependencies]
shadow-rs = { version = "{latest}", default-feature = false, features = ["tzdb"] }


[build-dependencies]
shadow-rs = { version = "{latest}", default-feature = false, features = ["tzdb"] }

```
Secondly, even if the project is split into two crates, the crates depended on via build-dependencies and dependencies will still be managed by the same Cargo.lock file. In reality, this does not reduce the number of crate dependencies.

**Comment by baoyachi** [comment] 2024-09-20 10:01
@metasim Based on the two points I answered above, can it solve your problem?

**Comment by metasim** [comment] 2024-09-20 20:31
@baoyachi 

> @metasim Based on the two points I answered above, can it solve your problem?

No. I'm not worried about crate dependencies. It's runtime dependencies on a shared library that the runtime functionality of my application doesn't need. As currently architected, `shadow-rs` is forcing applications to link in `libgit2` even when it's not needed at runtime. For example (on macOS):

```
$ cd shadow-rs
$ cargo build --examples
...
$ otool -L target/debug/examples/builtin_fn
target/debug/examples/builtin_fn:
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 2503.1.0)
	/opt/homebrew/opt/libgit2/lib/libgit2.1.8.dylib (compatibility version 1.8.0, current version 1.8.1)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.12)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1345.120.2)
```
I should be able to avail myself of the `git` functionality at compile time, but not depend on `libgit2` at runtime. 

I've actually switched to a different solution, so you can close this if you're not interested in pursuing it further.

**Comment by baoyachi** [comment] 2024-09-23 03:42
@metasim 
Thank you for your patient explanation. Feel free to reply if you have any questions. 

I'm temporarily closing it now.

**Closed by baoyachi** 2024-09-23 03:42 UTC
